package solver;
    dialect "java"
import com.example.domain.zuoxi.bean.Shift
import org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScoreHolder
import java.time.temporal.ChronoUnit
import java.time.Duration
import com.example.domain.zuoxi.bean.Employee
import com.example.domain.zuoxi.bean.EmployeeAvailability
import com.example.enums.AvailabilityType
import com.example.domain.zuoxi.bean.GroupPlan
import java.time.temporal.TemporalAdjusters;
global HardSoftScoreHolder scoreHolder;

rule "one employee can not work in the same day"
when
    $s : Shift(
                employeeId != null,
                $employeeId: employeeId,
                $startDate: startTime.toLocalDate(),
                $id:id)
    Shift(
            employeeId == $employeeId,
            $startDate == startTime.toLocalDate(),
            id>$id)
then
    scoreHolder.penalize(kcontext);
    //scoreHolder.addHardConstraintMatch(kcontext,-11);
    //System.out.println("one employee can not work in same day");
 end

rule "Break between non-consecutive shifts is at least 12 hours"
when
    $s : Shift(
            employeeId != null,
            $employeeId : employeeId,
            $leftEndDateTime: endTime)
    Shift(
            employeeId == $employeeId,
            $leftEndDateTime <= startTime,
            $leftEndDateTime.until(startTime, ChronoUnit.HOURS) < 12,
            this!=$s)
then
    //scoreHolder.addHardConstraintMatch(kcontext,-7);
    scoreHolder.penalize(kcontext);
    //System.out.println("Break between non-consecutive shifts is at least 12 hours");
end

rule "at most work 22 days"
    when
        Employee($id:id)
        //$s : Shift(employeeId == $id, $startDateTime : date)
        //Number($shiftCount:intValue > 22) from
        Number(intValue > 25||intValue< 16) from accumulate(
            $other : Shift(
                employeeId == $id//, $shiftStart : date,
                //$shiftEnd : endTime
            ),
            //$totalMinutes : sum(Duration.between($shiftStart, $shiftEnd).toMinutes()),
            count($other)
            //$shiftCount>2
            //$totalMinutes>600
        )
    then
        //System.out.println($shiftCount);
        //System.out.println($id+"大于2");
        scoreHolder.penalize(kcontext);
end

rule "Unavailable time slot for an employee"
    when
        $availability: EmployeeAvailability(
                state == AvailabilityType.UNAVAILABLE.getType(),
                $employeeId : employeeId,
                $startDateTime : startDateTime,
                $endDateTime : endDateTime)
        Shift(employeeId == $employeeId,
            $startDateTime <= endTime,
            $endDateTime >= startTime)
    then
        scoreHolder.penalize(kcontext);
end

rule "Desired time slot for an employee"
    when
        $availability: EmployeeAvailability(
                state == AvailabilityType.DESIRED.getType(),
                $employeeId : employeeId,
                $startDateTime : startDateTime,
                $endDateTime : endDateTime)
        Shift(employeeId == $employeeId,
            $startDateTime <= endTime,
            $endDateTime >= startTime)
    then
        scoreHolder.reward(kcontext);
end

rule "Undesired time slot for an employee"
    when
        $availability: EmployeeAvailability(
                state == AvailabilityType.UNDESIRED.getType(),
                $employeeId : employeeId,
                $startDateTime : startDateTime,
                $endDateTime : endDateTime)
        Shift(employeeId == $employeeId,
            $startDateTime <= endTime,
            $endDateTime >= startTime)
    then
        scoreHolder.penalize(kcontext);
end

rule "No more than 6 consecutive shifts"
    when
        Shift(
                $employeeId : employeeId,
                $firstStartDate : date)
        exists Shift(
                employeeId == $employeeId,
                $firstStartDate.plusDays(1) == date
                //$secondStartDate : startTime.toLocalDate()
                )
        exists Shift(
                employeeId == $employeeId,
                $firstStartDate.plusDays(2) == date
                )
        exists Shift(
                employeeId == $employeeId,
                $firstStartDate.plusDays(3) == date
                )
        exists Shift(
                employeeId == $employeeId,
                $firstStartDate.plusDays(4) == date
                )
        exists Shift(
                employeeId == $employeeId,
                $firstStartDate.plusDays(5) == date
                )
        exists Shift(
                employeeId == $employeeId,
                $firstStartDate.plusDays(6) == date
                )
    then
        scoreHolder.penalize(kcontext);
end
//与指定每天班组指定的班类型不一致
rule "shift type error"
    when
        Employee($id:id,$groupId:groupId)
        Shift(employeeId==$id,$shiftName:shiftName,$date:date)
        GroupPlan(groupId==$groupId,date==$date,!$shiftName.startsWith(shiftType))
    then
        scoreHolder.penalize(kcontext);
end

rule "same team need same shift in one day"
    when
        Employee($id:id,$groupId:groupId)
        Employee(id>$id,$id1:id,$groupId==groupId)
        Shift(employeeId==$id,$shiftName:shiftName,$date:date,$startTime:startTime,$sid:id)
        $s:Shift(employeeId==$id1,$shiftName!=shiftName,$date==date,$startTime1:startTime,$sid<id)
    then
        //System.out.println($sid+":"+$id+"%"+$id1+"ok");
        scoreHolder.penalize(kcontext,$s.getDuration($startTime)/10);
        //scoreHolder.addSoftConstraintMatch(kcontext,$s.getDuration($startTime));
end
rule "same team over 3 shift in one day"
    when
        Employee($id:id,$groupId:groupId)
        Employee(id>$id,$id1:id,$groupId==groupId)
        Employee(id>$id1,$id2:id,$groupId==groupId)
        Shift(employeeId==$id,$shiftName:shiftName,$date:date)
        Shift(employeeId==$id1,$shiftName!=shiftName,$date==date,$shiftName1:shiftName)
        exists Shift(employeeId==$id2,$shiftName!=shiftName,$date==date,$shiftName1!=shiftName)
    then
        //System.out.println($sid+":"+$id+"%"+$id1+"ok");
        scoreHolder.penalize(kcontext);
        //scoreHolder.addSoftConstraintMatch(kcontext,$s.getDuration($startTime));
end

//rule "same team need close shift in one day"
//    when
//        Employee($id:id,$groupId:groupId)
//        Employee(id>$id,$id1:id,$groupId==groupId)
//        Shift(employeeId==$id,$shiftName:shiftName,$date:date,$startTime:startTime,$sid:id)
//        $s:Shift(employeeId==$id1,$shiftName!=shiftName,$date==date,$startTime1:startTime,$sid<id)
//    then
//        //System.out.println($id+":"+$id1+"::"+$s.getDuration($startTime));
//        scoreHolder.penalize(kcontext,$s.getDuration($startTime));
//end

rule "overnight need rest for 2 days"
    when
        Shift($employeeId:employeeId,shiftName.startsWith("F"),$date:date) &&
        (exists Shift(employeeId==$employeeId,$date==date.minusDays(1))||exists Shift(employeeId==$employeeId,$date==date.minusDays(2)))
    then
        //System.out.println($employeeId+":overnight need rest for 2 days"+$date);
        scoreHolder.penalize(kcontext);
end
rule "no rest work rest"
    when
        Shift($employeeId:employeeId,$date:date,date.getDayOfMonth()!=1,checkLast(),$pdate:date.minusDays(1),$mdate:date.minusDays(1))
        not(Shift(employeeId==$employeeId,(date==$pdate||date==$mdate)))
        //not(Shift(employeeId==$employeeId,$date==date.plusDays(1)))
    then
        //System.out.println($employeeId+":"+$date+"no rest work rest");
        scoreHolder.penalize(kcontext);
end
/*
rule "test not"
    when
        not(Shift(employeeId==3))
    then
        System.out.println("test not:");
end
rule "test forall"
    when
        exists(Employee())
        forall(Shift(employeeId in (1,3)))
    then
        System.out.println("员工所有都是1或3");
end
rule "test1"
    //activation-group "g1"
    when
        Shift(id>1&&<5,$id:id)
    then
        System.out.println("11111:"+$id);
end
rule "test2"
activation-group "g1"
salience 4
    when
    then
        System.out.println("22222");
end
rule "test3"
activation-group "g1"
salience 3
    when
    then
        System.out.println("33333");
end
*/




